---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: debian:testing
    pre_build_image: true
    # Keep container running so Ansible can exec into it
    command: sleep infinity

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible
